### ISSUE TITLE
Two words variants not working

### ISSUE THREAD

**Issue by fraincs** [ismamz/postcss-get-color#1]
Only Vibrant and Muted works 
VibrantDark, VibrantLight, MutedLight and VibrantLight are throwing errors.

Unknown name color: MutedLight

**Comment by ismamz** [comment]
This is because the image doesn't have these colors. The plugin will take the first color in palette.
But, do you have the same problem with more than one image? Send me the image if you can.

**Comment by ismamz** [comment]
The color name is `LightMuted`. You used `MutedLight`.

```
var colorNames = [
    'Vibrant',
    'Muted',
    'DarkVibrant',
    'DarkMuted',
    'LightVibrant',
    'LightMuted'
];
```

There are a problem with the documentation. I will fix it now!
Thank you for notify me!
